Importing numpy as np

In [1]:
import numpy as np

En numpy un escalar es un solo elemento, un vector es una lista, una lista bidimensional es una matriz, 3 o mas-dimensional es un tensor

In [3]:
# crear una lista con numpy de 1 dimension (vector)
mi_lista = [1,2,3,4,5,6]
lista_numpy = np.array(mi_lista)
print(lista_numpy)

[1 2 3 4 5 6]


In [6]:
lista_digitos = np.arange(0,10,1) # arange(start, stop, step non inclusive)
print(lista_digitos)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
lista_digitos2 = np.linspace(start=0,stop=10,num=10) #create num elementos entre el star y el stop que esten equivalentemente espaciados, si incluye al ultimo
lista_digitos2

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [32]:
ceros = np.zeros(10) # crea lista de X numero de ceros/unos
print(ceros)
unos = np.ones(10)
print(unos)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [37]:
fulls = np.full(2,3) # crea una lista con 2 elementos que valen 3
print(fulls)
# otra forma es con shape y fill_value
fulls2 = np.full(shape=(5,2), fill_value=0) # crea 5 listas de 2 elementos, cada elemento es 0 (matriz pues es una lista de listas, es decir bidimensional)
print(fulls2)

[3 3]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# se pueden crear copias de un np.full y cambiarles el valor a cada elemento asi
base = np.full(shape=(4,3), fill_value=4.345)
print(base)
print("====================")
nueva_base = np.full_like(base, np.pi) # np.pi es pi

[[4.345 4.345 4.345]
 [4.345 4.345 4.345]
 [4.345 4.345 4.345]
 [4.345 4.345 4.345]]
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


Otra forma es crear arrays ya no con datos predefinidos sino aleatorios, para eso se usan estos metodos

In [45]:
array_aleatorio = np.random.rand(3,2) # retorna una matriz m x n con datos del 0 al 1
array_aleatorio

array([[0.35360826, 0.7872959 ],
       [0.28152416, 0.071897  ],
       [0.13826965, 0.27312125]])

In [48]:
array_enteros = np.random.randint(low=2, high=4, size=(4,2))
array_enteros

array([[2, 2],
       [3, 3],
       [3, 3],
       [2, 2]])

In [50]:
distribucion_gausiana_normal = np.random.normal(loc=5, scale=1, size=(3,2))
distribucion_gausiana_normal

array([[4.75965066, 4.87319067],
       [5.3646093 , 2.46824445],
       [4.49574011, 6.90652854]])

In [53]:
# flatten lleva cualquier aray a 1 Dimesion
flatten_ejemplo = np.random.randint(low=5,high=10,size=(2,3,4))
print(flatten_ejemplo.flatten())


[8 7 5 8 5 5 9 8 5 5 6 8 6 5 7 8 5 7 8 8 5 9 5 5]


Se puede hacer slicing usando [ ]

In [56]:
lista2 = np.random.randint(low=1, high=10, size=(3,4))
print(lista2)

[[7 5 8 3]
 [4 7 7 9]
 [6 9 6 8]]


In [62]:
lista2[1:3,:1]

array([[4],
       [6]])

Se puede copiar un numpy array usando *.copy() o simplemente np.array(*array a copiar*)