Importing numpy as np

In [1]:
import numpy as np

En numpy un escalar es un solo elemento, un vector es una lista, una lista bidimensional es una matriz, 3 o mas-dimensional es un tensor

In [3]:
# crear una lista con numpy de 1 dimension (vector)
mi_lista = [1,2,3,4,5,6]
lista_numpy = np.array(mi_lista)
print(lista_numpy)

[1 2 3 4 5 6]


In [6]:
lista_digitos = np.arange(0,10,1) # arange(start, stop, step non inclusive)
print(lista_digitos)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
lista_digitos2 = np.linspace(start=0,stop=10,num=10) #create num elementos entre el star y el stop que esten equivalentemente espaciados, si incluye al ultimo
lista_digitos2

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [32]:
ceros = np.zeros(10) # crea lista de X numero de ceros/unos
print(ceros)
unos = np.ones(10)
print(unos)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [37]:
fulls = np.full(2,3) # crea una lista con 2 elementos que valen 3
print(fulls)
# otra forma es con shape y fill_value
fulls2 = np.full(shape=(5,2), fill_value=0) # crea 5 listas de 2 elementos, cada elemento es 0 (matriz pues es una lista de listas, es decir bidimensional)
print(fulls2)

[3 3]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# se pueden crear copias de un np.full y cambiarles el valor a cada elemento asi
base = np.full(shape=(4,3), fill_value=4.345)
print(base)
print("====================")
nueva_base = np.full_like(base, np.pi) # np.pi es pi

[[4.345 4.345 4.345]
 [4.345 4.345 4.345]
 [4.345 4.345 4.345]
 [4.345 4.345 4.345]]
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


Otra forma es crear arrays ya no con datos predefinidos sino aleatorios, para eso se usan estos metodos